### ISSUE TITLE
var m1 not used

### ISSUE THREAD

**Issue by lucacervello** [alessandrotonella/lp-ocaml#1]
La variabile m1 non é usata e non so perché gli assegni il valore con <-

https://github.com/alessandrotonella/lp-ocaml/blob/master/ex3.ml#L29

**Comment by alessandrotonella** [comment]
Uso l'operatore <- perchè così ci ha spiegato a lezione.
Se non non assegno let m1 dice che il tipo restituito non va bene

**Comment by lucacervello** [comment]
Quindi tratti m come una variabile e gli cambi il valore ?

**Comment by alessandrotonella** [comment]
Si l'idea era quella. Ora ho cambiato perché mi sembrava un po' contorto quello che avevo fatto prima.

**Comment by lucacervello** [comment]
Riscritto e ora non c'é piú
